### ISSUE TITLE
Upgrade old pnext builds

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump#14]
@mmnosek is having problem with migrating/updating a Starcounter version 2.3.0.4787 (Nov 2016) database to latest RC (Jan 2017). When I run the StarDump unload command, the following error is given.
```
C:\Github\Starcounter\StarDump\src\StarDump> dotnet run unload --database=default --dump=C:/Temp/dump.sqlite3
Project StarDump.Common (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project Starcounter.Abstractions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Configuration (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Interop (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Error (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Management (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Starcounter.X6Decimal (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Database (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Starcounter.AspNetCore (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Starcounter (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project StarDump.Core (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project StarDump (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Unload started C:/Temp/dump.sqlite3

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'star_run_message_loop' in DLL 'sccoredb'.
   at Starcounter.Database.Interop.sccoredb.star_run_message_loop()
   at Starcounter.Database.Hosting.Connection.ProcessCallbackMessagesThread()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)


Usage:  unload [options]

Options:
  -db | --database <DatabaseName>               Name of starcounter database to dump
  -d | --dump <DumpFileName>                    Output dump filename
  -b | --buffersize <BufferSize>                Set insert rows buffer size to dump database.
  -scp | --skipcolumnprefixes <ColumnPrefixes>  Column prefixes to skip, space and/or comma separated. Example: -scp="a b,c"
  -stp | --skiptableprefixes <TablePrefixes>    Table prefixes to skip, space and/or comma separated. Example: -scp="a b,c"
  -? | -h | --help                              Show help information

System.EntryPointNotFoundException: Unable to find an entry point named 'star_init_metalayer' in DLL 'scdbmetalayer'.
   at Starcounter.Database.Interop.scdbmetalayer.star_init_metalayer(UInt64 context_handle)
   at Starcounter.Database.Context.RunMetalayerContinuations() in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Context.cs:line 87
   at Starcounter.Database.Context.Initialize(UInt32 maxContexts) in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Context.cs:line 111
   at Starcounter.Database.Hosting.Connection.ConnectToDataManager(Options options) in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Hosting\Connection.cs:line 155
   at Starcounter.Database.Hosting.Connection.Start() in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Hosting\Connection.cs:line 60
   at Starcounter.Database.Hosting.DefaultAppHost.Start() in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Hosting\DefaultAppHost.cs:line 26
   at StarDump.Core.Unload.Run() in C:\Github\Starcounter\StarDump\src\StarDump.Core\Unload.cs:line 46
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\Github\Starcounter\StarDump\src\StarDump.Core\CommandInterface.cs:line 62
   at StarDump.CommandLineInterface.<>c__DisplayClass8_1.<AddUnloadCommand>b__1() in C:\Github\Starcounter\StarDump\src\StarDump\CommandLineInterface.cs:line 120
```

It seems like there are some Starcounter versions between 2.2 and 2.3 RC (old pnext builds) which are not compatible with StarDump or the current [2.2 migrator tool](https://github.com/Starcounter/StarDump.Migrator.2.2)

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/CompanyTrack/issues/282

**Comment by miyconst** [comment]
@ubbeK, @mmnosek, please add some more info.

Are you using the pre-compiled exe or building and starting the app from the sources? Please try to compile `Starcounter.Core` and run the `MinimalApp` under `2.3.0.4787`. If that works, then try to compile StarDump and unload the database.

If that is not working, then there is nothing we (me and @ubbeK) can do, since that version does not support `Starcounter.Core` and we have to find out another solution.

**Comment by ubbeK** [comment]
The same error when running MinimalApp

```
C:\Github\Starcounter\Starcounter.Core\samples\MinimalApp> dotnet run
Project Starcounter.Abstractions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Configuration (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Interop (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Error (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Management (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Starcounter.X6Decimal (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Starcounter.Database (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Starcounter.AspNetCore (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Starcounter (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project MinimalApp (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'star_run_message_loop' in DLL 'sccoredb'.
   at Starcounter.Database.Interop.sccoredb.star_run_message_loop()
   at Starcounter.Database.Hosting.Connection.ProcessCallbackMessagesThread() in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Hosting\Connection.cs:line 135
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'star_init_metalayer' in DLL 'scdbmetalayer'.
   at Starcounter.Database.Interop.scdbmetalayer.star_init_metalayer(UInt64 context_handle)
   at Starcounter.Database.Context.RunMetalayerContinuations() in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Context.cs:line 87
   at Starcounter.Database.Context.Initialize(UInt32 maxContexts) in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Context.cs:line 111
   at Starcounter.Database.Hosting.Connection.ConnectToDataManager(Options options) in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Hosting\Connection.cs:line 155
   at Starcounter.Database.Hosting.Connection.Start() in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Hosting\Connection.cs:line 60
   at Starcounter.Database.Hosting.DefaultAppHost.Start() in C:\Github\Starcounter\Starcounter.Core\src\Starcounter.Database\Hosting\DefaultAppHost.cs:line 26
   at MinimalApp.Program.Main(String[] args) in C:\Github\Starcounter\Starcounter.Core\samples\MinimalApp\Program.cs:line 76
```

**Comment by miyconst** [comment]
@ubbeK thank you for the investigation.

So, the answer is simple, the old version of Starcounter 2.3 lacks some API methods required for Starcounter.Core.

We can create a Starcounter.Migrator.2.3 app, but I am not sure whether it is reasonable.

cc @dan31

**Comment by ubbeK** [comment]
> We can create a Starcounter.Migrator.2.3 app, but I am not sure whether it is reasonable.

Agreed, would not like to make a specific migrator tool each time the api changed for unreleased starcounter versions. But at the same time we cannot let @mmnosek hanging. Lets see what @dan31 say.

**Comment by mmnosek** [comment]
Guys, thanks for investigation. At my case, it doesn't block me anymore. It was on the test environment so we decided to delete all data because we needed RC version. So please don't consider this issue as blocking for me :)

**Comment by ubbeK** [comment]
@mmnosek Thanks for letting us know!

**Comment by miyconst** [comment]
Closing this issue as won't be fixed.
