### ISSUE TITLE
System.AggregateException, while trying to reload

### ISSUE THREAD

**Issue by andwah** [Starcounter/StarDump#16]
```
System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Unable to cast object of type 'System.Double' to type 'System.String'.))) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (Unable to cast object of type 'System.Double' to type 'System.String'.)) ---> System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Double' to type 'System.String'.) ---> System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.String'.
   at StarDump.Common.SqlHelper.ConvertFromSqliteToStarcounter(String starcounterDataTypeName, Object value) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Common\Helpers\SqlHelper.cs:line 309
   at StarDump.Core.Reload.InsertTableData(SqliteConnection cn, ReloadTable table, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 201
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 143
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 153
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 153
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at StarDump.Core.Reload.CreateTablesAndInsertData(SqliteConnection cn, Int32& tablesCount, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 119
   at StarDump.Core.Reload.Run() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 55
   at StarDump.Core.CommandInterface.Reload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\CommandInterface.cs:line 36
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddReloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump\CommandLineInterface.cs:line 172
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (One or more errors occurred. (Unable to cast object of type 'System.Double' to type 'System.String'.)) ---> System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Double' to type 'System.String'.) ---> System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.String'.
   at StarDump.Common.SqlHelper.ConvertFromSqliteToStarcounter(String starcounterDataTypeName, Object value) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Common\Helpers\SqlHelper.cs:line 309
   at StarDump.Core.Reload.InsertTableData(SqliteConnection cn, ReloadTable table, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 201
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 143
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 153
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 153
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Double' to type 'System.String'.) ---> System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.String'.
   at StarDump.Common.SqlHelper.ConvertFromSqliteToStarcounter(String starcounterDataTypeName, Object value) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Common\Helpers\SqlHelper.cs:line 309
   at StarDump.Core.Reload.InsertTableData(SqliteConnection cn, ReloadTable table, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 201
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 143
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 153
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.String'.
   at StarDump.Common.SqlHelper.ConvertFromSqliteToStarcounter(String starcounterDataTypeName, Object value) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Common\Helpers\SqlHelper.cs:line 309
   at StarDump.Core.Reload.InsertTableData(SqliteConnection cn, ReloadTable table, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 201
   at StarDump.Core.Reload.<>c__DisplayClass19_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-1057\StarDump\src\StarDump.Core\Reload.cs:line 143
   at System.Threading.Tasks.Task.Execute()<---
<---
<---
```

**Comment by andwah** [comment]
Forgot to add, I have a dump and trying to reload it in Starcounter version 2.3.0.5465

**Comment by miyconst** [comment]
Can you please share the dump via a zip archive through dropbox?

**Comment by miyconst** [comment]
Fixed in this commit - https://github.com/Starcounter/StarDump/commit/945030dad19c5378129243f311507bc6203a5f92.

**Note:** after the fix the decimal values will be unloaded as string, but current dump with doubles for decimals will also work for reloading.
