### ISSUE TITLE
Error unloading Starcounter.Core tests database

### ISSUE THREAD

**Issue by linkdata** [Starcounter/StarDump#28]
Mark the issue as `invalid` if this is not supposed to work right now.

From `Starcounter.Core/tests/Starcounter.Core.Tests`
> dotnet test

Then from `Program Files/Starcounter/stardump`:

> stardump unload

```
Unload started C:\Users\Johan\AppData\Local\Temp\stardump-default-2017.01.31-12.43.sqlite3


Usage:  unload [options]

Options:
  -db | --database <DatabaseName>               Name of starcounter database to dump
  -f | --file <FileName>                        Output dump filename
  -b | --buffersize <BufferSize>                Set insert rows buffer size to dump database.
  -scp | --skipcolumnprefixes <ColumnPrefixes>  Column prefixes to skip, space and/or comma separated. Example: -scp="a b,c"
  -stp | --skiptableprefixes <TablePrefixes>    Table prefixes to skip, space and/or comma separated. Example: -stp="a b,c"
  -? | -h | --help                              Show help information

System.NotImplementedException: The data type [InheritsWithReference] is not supported.
   at StarDump.Core.CrudHelper.GetMethod(String dataTypeName, Boolean nullable) in C:\TeamCity\BuildAgent\work\sc-2087\StarDump\src\StarDump.Core\Helpers\CrudHelper.cs:line 167
   at StarDump.Core.CrudHelper..ctor(UInt64 dbHandle, UnloadTable table) in C:\TeamCity\BuildAgent\work\sc-2087\StarDump\src\StarDump.Core\Helpers\CrudHelper.cs:line 28
   at StarDump.Core.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\TeamCity\BuildAgent\work\sc-2087\StarDump\src\StarDump.Core\Unload.cs:line 67
   at Starcounter.Core.Database.Transaction.RunSyncHelper(Object obj)
   at Starcounter.Core.Database.Context.Send(Transaction cxt, SendOrPostCallback d, Object state)
   at Starcounter.Core.TransactHelper.Transact(Transaction tran, Action action, Action onCommit)
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-2087\StarDump\src\StarDump.Core\Unload.cs:line 56
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-2087\StarDump\src\StarDump.Core\CommandInterface.cs:line 76
   at StarDump.CommandLineInterface.<>c__DisplayClass8_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-2087\StarDump\src\StarDump\CommandLineInterface.cs:line 120
```

**Comment by linkdata** [comment]
Assigning to me, as I think this is due to me messing with NuGet things.

**Comment by miyconst** [comment]
What is the `[InheritsWithReference]` type? This exception is thrown when a property of a database class has some not supported format, such as `byte[]`.

Can you please share your database or check via Starcounter administrator what table has that column?

**Comment by miyconst** [comment]
This issue should now be fixed. See the commit referenced above.
