### ISSUE TITLE
Exception in StarDump! 

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/StarDump#42]
BackUp data seems correct! but,
```
StarDump application version:    0.1.2
SQLite dump format version:      0.0.2

C:\Program Files\Starcounter\StarDump>StarDump unload -db tabletennis -f C:\Star
counter\YDK\TableTennis
Unload started C:\Starcounter\YDK\TableTennis.sqlite3
04/04/2017 05:42:39: 500 TTDB.MacSonuc rows unloaded
04/04/2017 05:42:39: 500 TTDB.MacSonuc rows unloaded
04/04/2017 05:42:39: 500 TTDB.MacSonuc rows unloaded
04/04/2017 05:42:39: 500 TTDB.MacSonuc rows unloaded
04/04/2017 05:42:39: 500 TTDB.MacSonuc rows unloaded
04/04/2017 05:42:39: 500 TTDB.MacSonuc rows unloaded
04/04/2017 05:42:39: 500 TTDB.Mac rows unloaded
04/04/2017 05:42:39: 500 TTDB.Mac rows unloaded


Usage:  unload [options]

Options:
  -db | --database <DatabaseName>               Name of starcounter database to
dump
  -f | --file <FileName>                        Output dump filename
  -b | --buffersize <BufferSize>                Set insert rows buffer size to d
ump database.
  -scp | --skipcolumnprefixes <ColumnPrefixes>  Column prefixes to skip, space a
nd/or comma separated. Example: -scp="a b,c"
  -stp | --skiptableprefixes <TablePrefixes>    Table prefixes to skip, space an
d/or comma separated. Example: -stp="a b,c"
  -? | -h | --help                              Show help information

System.AggregateException: One or more errors occurred. (An error occurred while
 sending the request.) ---> System.Net.Http.HttpRequestException: An error occur
red while sending the request. ---> System.Net.Http.WinHttpException: A connecti
on with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at StarDump.Core.StarcounterConfiguration.GetCurrentConfiguration() in C:\Tea
mCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\Model\StarcounterConfig
uration.cs:line 24
   at StarDump.Core.Unload.InsertMetaInfo(SqliteConnection cn, DateTime unloadSt
art, DateTime unloadFinish, Int32 tablesCount, UInt64 rowsCount) in C:\TeamCity\
BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\Unload.cs:line 362
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-4407\StarDump
\src\StarDump.Core\Unload.cs:line 137
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output)
 in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\CommandInterf
ace.cs:line 76
   at StarDump.CommandLineInterface.<>c__DisplayClass8_1.<AddUnloadCommand>b__1(
) in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump\CommandLineInterf
ace.cs:line 120
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurre
d while sending the request. ---> System.Net.Http.WinHttpException: A connection
 with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()<---
```
![image](https://cloud.githubusercontent.com/assets/3463333/24643259/84c65872-1915-11e7-9ff7-e5c75a784a77.png)

**Comment by SenerDemiral** [comment]
Same exception 
StarDump application version:    0.1.3

**Comment by miyconst** [comment]
@SenerDemiral thank you for reporting, I am looking into it. One thing I would like to ask you is to properly format the exception stack trace. Example:

```
System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at StarDump.Core.StarcounterConfiguration.GetCurrentConfiguration() in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\Model\StarcounterConfiguration.cs:line 24
   at StarDump.Core.Unload.InsertMetaInfo(SqliteConnection cn, DateTime unloadStart, DateTime unloadFinish, Int32 tablesCount, UInt64 rowsCount) in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\Unload.cs:line 362
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\Unload.cs:line 137
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\CommandInterface.cs:line 76
   at StarDump.CommandLineInterface.<>c__DisplayClass8_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump\CommandLineInterface.cs:line 120
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()<---
```

**Comment by miyconst** [comment]
@SenerDemiral it looks like there is a bug which is already fixed.

Please try Starcounter `2.4.0.1566` and let me know how it works.

**Comment by SenerDemiral** [comment]
I already tried 2.4.0.1566 (StarDump v0.1.3).
Same exception exists there.

Windows 2012 R2 command prompt window is not adjustable, this is why format is not properly.

**Comment by miyconst** [comment]
>I already tried 2.4.0.1566 (StarDump v0.1.3).
Same exception exists there.

Thanks for checking. Looks like it is not related to any bugs, but not started Starcounter server causes this error.

Please make sure that Starcounter server is started and database is stopped prior to unload. Currently there is an issue which prevents StarDump from connecting to a database if it's already started - [Unable to connect to a started database](https://github.com/Starcounter/Starcounter.Core/issues/157).

**Comment by miyconst** [comment]
Another note: if you experience the same issue as linked above, but your database is not started, then please start the database, stop it, and try unload again.

**Comment by SenerDemiral** [comment]
Yes, you are right, it worked now.
I didn't stop DataBase. (Habit of old SQL)

By the way, I couldn't open above link. (Unable to connect to a started database.) Page not found!
```
StarDump application version:    0.1.3
SQLite dump format version:      0.0.2

C:\Program Files\Starcounter\StarDump>StarDump unload -db tabletennis -f C:\Star
counter\YDK\TableTennis
Unload started C:\Starcounter\YDK\TableTennis.sqlite3
04/04/2017 09:45:57: 500 TTDB.MacSonuc rows unloaded
04/04/2017 09:45:57: 500 TTDB.MacSonuc rows unloaded
04/04/2017 09:45:57: 500 TTDB.MacSonuc rows unloaded
04/04/2017 09:45:57: 500 TTDB.MacSonuc rows unloaded
04/04/2017 09:45:57: 500 TTDB.MacSonuc rows unloaded
04/04/2017 09:45:57: 500 TTDB.MacSonuc rows unloaded
04/04/2017 09:45:57: 500 TTDB.Mac rows unloaded
04/04/2017 09:45:57: 500 TTDB.Mac rows unloaded
Unload finished C:\Starcounter\YDK\TableTennis.sqlite3
Elapsed 00:00:16.3242379
Tables count 10
Rows count 5076
```
