### ISSUE TITLE
GetCurrentConfiguration crashes if Starcounter server is not started

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#43]
Original issue - [Exception in StarDump! Starcounter v2.4.0.1555](https://github.com/Starcounter/StarDump/issues/42).

StarDump crashes trying to retrieve database configuration if Starcounter server is not started.

The exception text should point to the fact that Starcounter server has to be started instead of showing misleading one.

```
System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at StarDump.Core.StarcounterConfiguration.GetCurrentConfiguration() in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\Model\StarcounterConfiguration.cs:line 24
   at StarDump.Core.Unload.InsertMetaInfo(SqliteConnection cn, DateTime unloadStart, DateTime unloadFinish, Int32 tablesCount, UInt64 rowsCount) in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\Unload.cs:line 362
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\Unload.cs:line 137
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump.Core\CommandInterface.cs:line 76
   at StarDump.CommandLineInterface.<>c__DisplayClass8_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-4407\StarDump\src\StarDump\CommandLineInterface.cs:line 120
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()<---
```

**Comment by ubbeK** [comment]
I cannot recreate this issue:

```
C:\Program Files\Starcounter\StarDump> star -v
Version=2.3.1.6490
C:\Program Files\Starcounter\StarDump> staradmin kill all
C:\Program Files\Starcounter\StarDump> .\StarDump.exe unload --database=stardump --file=C:\Temp\test.sqlite3
Unload started C:\Temp\test.sqlite3
Unload finished C:\Temp\test.sqlite3
Elapsed 00:00:01.3235111
Tables count 267
Rows count 23
```

**Comment by miyconst** [comment]
I have already fixed this issue, quite some time ago. Sorry for keeping it open.
