### ISSUE TITLE
unload --skipcolumnprefixes argument exception

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/StarDump#53]
StarDump crashes when using `--skipcolumnprefixes` argument

```
dotnet run unload --database=default --file=C:\Temp\UnloadedSkipColumnArgumentTestDump.sqlite3 --skipcolumnprefixes="intField nullableIntFie"
Unload started C:\Temp\UnloadedSkipColumnArgumentTestDump.sqlite3

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Starcounter.Core.Interop.sccrud.star_crud_ReadString(UInt64 context_handle, UInt64 property_read_handle, UInt64 object_id, UInt64 object_ref, IntPtr& value)
   at Starcounter.Core.Database.DbCrud.GetString(UInt64 dbId, UInt64 dbRef, UInt64 crudHandle)
   at StarDump.Core.CrudHelper.<>c.<GetMethod>b__15_0(UInt64 dbId, UInt64 dbRef, UInt64 getter) in C:\Github\Starcounter\StarDump\src\StarDump.Core\Helpers\CrudHelper.cs:line 133
   at StarDump.Core.CrudHelper.GetValue(UInt64 dbId, UInt64 dbRef, String columnName) in C:\Github\Starcounter\StarDump\src\StarDump.Core\Helpers\CrudHelper.cs:line 66
   at StarDump.Core.UnloadTable.FillRow(DumpRow row) in C:\Github\Starcounter\StarDump\src\StarDump.Core\Model\UnloadTable.cs:line 42
   at StarDump.Core.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\Github\Starcounter\StarDump\src\StarDump.Core\Unload.cs:line 100
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Unload.Run() in C:\Github\Starcounter\StarDump\src\StarDump.Core\Unload.cs:line 58
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\Github\Starcounter\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\Github\Starcounter\StarDump\src\StarDump\CommandLineInterface.cs:line 181
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at StarDump.CommandLineInterface.Execute(String[] args) in C:\Github\Starcounter\StarDump\src\StarDump\CommandLineInterface.cs:line 38
   at StarDump.Program.Main(String[] args) in C:\Github\Starcounter\StarDump\src\StarDump\Program.cs:line 19
```

## Steps to reproduce

1. Recreate default database
2. Build and deploy [StarDumpTestDumpData](https://github.com/Starcounter/StarDump/tree/master/test/StarDumpTestDumpData) (Starcounter version 2.3.1.X application)
3. execute command in [StarDump console application root](https://github.com/Starcounter/StarDump/tree/master/src/StarDump): `dotnet run unload --database=default --file=C:\Temp\UnloadedSkipColumnArgumentTestDump.sqlite3 --skipcolumnprefixes="intField nullableIntFie"`

**Comment by ubbeK** [comment]
The reason behind this bug is that the default value for `--skipcolumnprefixes` argument is `__` and when setting this argument manually, it gets overridden. Hence, we should combine the default value of `--skipcolumnprefixes` with the manually selected `--skipcolumnprefixes`.

**Comment by ubbeK** [comment]
This has been implemented, closing.
