### ISSUE TITLE
StarDump unload - Instantiation of a object failed because the object wasn't a registered type

### ISSUE THREAD

**Issue by habib535** [Starcounter/StarDump#54]
Connect to _Playground Europe_ EC2 Instance on AWS and try to dump the insidestarcounter database

`stardump unload --database insidestarcountercom --file C:\Users\Administrator\Desktop\Dump\Dump`

Creates the Dump.sqlite3 file but all tables are empty and thorws the following exception
 
```
Starcounter.Core.ScErrObjectNotAType: ScErrObjectNotAType (SCERR4019): Instantiation of a object failed because the object wasn't a registered type. TypeId=37
   at Starcounter.Core.Db.FromIdRef(UInt64 dbId, UInt64 dbRef)
   at Starcounter.Core.Database.SQLEnumerator`1.GetCurrentGeneric(SQLEnumerator`1 enumerator)
   at StarDump.Core.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\TeamCity\BuildAgent\work\sc-5672\StarDump\src\StarDump.Core\Unload.cs:line 88
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-5672\StarDump\src\StarDump.Core\Unload.cs:line 132
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-5672\StarDump\src\StarDump.Core\CommandInterface.cs:line 76
   at StarDump.CommandLineInterface.<>c__DisplayClass8_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-5672\StarDump\src\StarDump\CommandLineInterface.cs:line 135
```
I wanted to skip the TypeId=37 from the Dump but am unable to track it in the database. Tried to query different metadata tables with no luck like
`Starcounter.Metadata.RawView`
`Starcounter.Internal.Metadata.MotherOfAllLayouts`

How do I get the table name of TypeId=37?

**Comment by habib535** [comment]
@alemoi @warpech

**Comment by miyconst** [comment]
Only @ubbeK and me can help with this issue.

**Comment by habib535** [comment]
Hi, I am trying to debug stardump on the server but now the error is different
```
Starcounter.Core.StarcounterException: ScErrDataManagerUnavailable (SCERR4293): Failed to connect to data manager is unavailable. Occurs when data manager is not started or not yet properly initialized.
   at Starcounter.Core.Hosting.Connection.ConnectToDataManager(StarcounterOptions options)
   at Starcounter.Core.Hosting.Connection.Start()
   at Starcounter.Core.Hosting.DefaultAppHost.Start()
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-6711\StarDump\src\StarDump.Core\Unload.cs:line 47
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-6711\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-6711\StarDump\src\StarDump\CommandLineInterface.cs:line 181

```
In the log file only the following message is written.
`20170803T143601 Notice sc://win-evq4ef52rs2/personal/insidestarcountercom Starcounter - The host has been disconnected.`

Found a similar issue https://github.com/Starcounter/RebelsLounge/issues/90. The root cause identified in this thread was that the Starcounter.Core is not able to properly identify correct database installation and was fixed but seems like this has started happening again.

@miyconst can you hint some guesses on what might be the cause or some other way of debugging?

**Comment by habib535** [comment]
I am back to the original error with a different TypeId this time.

```
ScErrObjectNotAType (SCERR4019): Instantiation of a object failed because the object wasn't a registered type. TypeId=81
   at Starcounter.Core.Db.FromIdRef(UInt64 dbId, UInt64 dbRef)
   at Starcounter.Core.Database.SQLEnumerator`1.GetCurrentGeneric(SQLEnumerator`1 enumerator)
   at StarDump.Core.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\Users\Administrator\Documents\Starcounter\Workspace\StarDump\src\StarDump.Core\Unload.cs:line 91
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Unload.Run() in C:\Users\Administrator\Documents\Starcounter\Workspace\StarDump\src\StarDump.Core\Unload.cs:line 61
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\Users\Administrator\Documents\Starcounter\Workspace\StarDump\src\StarDump.Core\CommandInterface.cs:line 79
```
Error is happening on line 91 where the Enumerator is unable to convert an object to DB Type
![image](https://user-images.githubusercontent.com/2991381/28936982-a8ce6f1a-7889-11e7-9665-f7548514c513.png)

How can I get table name by TypeId?
Why I can't query MotherOfAllLayouts using starcounter admin UI?

![image](https://user-images.githubusercontent.com/2991381/28936739-eca46574-7888-11e7-9b64-1ae802bb1994.png)

**Comment by ubbeK** [comment]
Lets debug this together when you come in to the office.

**Comment by bouguila** [comment]
I am also unable to make a dump of insidestarcounter.com DB

`Starcounter.Core.ScErrObjectNotAType: ScErrObjectNotAType (SCERR4019): Instantiation of a object failed because the object wasn't a registered type. TypeId=86
   at Starcounter.Core.Db.FromIdRef(UInt64 dbId, UInt64 dbRef)
   at Starcounter.Core.Database.DbCrud.GetIDbProxy(UInt64 dbId, UInt64 dbRef, UInt64 crudHandle)
   at StarDump.Core.CrudHelper.GetReference(UInt64 dbId, UInt64 dbRef, UInt64 getter) in C:\TeamCity\BuildAgent\work\sc-8353\StarDump\src\StarDump.Core\Helpers\
CrudHelper.cs:line 179
   at StarDump.Core.CrudHelper.<GetMethod>b__15_14(UInt64 dbId, UInt64 dbRef, UInt64 getter) in C:\TeamCity\BuildAgent\work\sc-8353\StarDump\src\StarDump.Core\H
elpers\CrudHelper.cs:line 147
   at StarDump.Core.UnloadTable.FillRow(DumpRow row) in C:\TeamCity\BuildAgent\work\sc-8353\StarDump\src\StarDump.Core\Model\UnloadTable.cs:line 40
   at StarDump.Core.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\TeamCity\BuildAgent\work\sc-8353\StarDump\src\StarDump.Core\Unload.cs:line 101
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-8353\StarDump\src\StarDump.Core\Unload.cs:line 132
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-8353\StarDump\src\StarDump.Core\CommandInterf
ace.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-8353\StarDump\src\StarDump\CommandLineInterf
ace.cs:line 182`

cc @miyconst

**Comment by miyconst** [comment]
I will take care of the issue, it seems to be simpler than I expected.

**Comment by miyconst** [comment]
@habib535, @bouguila what is your Starcounter version?

**Comment by bouguila** [comment]
Starcounter version 2.3.1.7204

**Comment by miyconst** [comment]
@bouguila I thought you are using `2.4.x`, will have to dig deeper.

**Comment by bouguila** [comment]
upgrading to 2.31.7252 does not fix the problem.

**Comment by miyconst** [comment]
It turns out that the issue is deeper than expected, it's under investigation.

**Comment by miyconst** [comment]
The source of this issue was - [Determine object type by it's SetSpecifier not LayoutHandle](https://github.com/Starcounter/Starcounter.Core/issues/205), a workaround is not implemented, and should be available in the next nightly build.

**Comment by miyconst** [comment]
A work around is implemented and tested by @bouguila.
