### ISSUE TITLE
Starcounter.Core.StarcounterException: ScErrBadArguments (SCERR1001): One or more arguments was invalid. Property Deleted isn't found in class Simplified.Ring6.WebSection.

### ISSUE THREAD

**Issue by warpech** [Starcounter/StarDump#69]
I have a SQLite dump (https://drive.google.com/file/d/0BzF8KHDi0CnNSGQzaHFmRWNlSWM/view?usp=sharing) created using Starcounter 2.3.1.7555 that I try to reload in Starcounter 2.3.1.7558.

The dump contains data in Simplified data model, which wasn't significantly since weeks: https://github.com/StarcounterApps/Simplified/commits/master

Trying to use `C:\Program Files\Starcounter\StarDump>StarDump.exe reload --database default --file C:\www\WebsiteEditor-issue-257.sqlite3` results in:

```
Starcounter.Core.StarcounterException: ScErrBadArguments (SCERR1001): One or more arguments was invalid. Property Deleted isn't found in class Simplified.Ring6.WebSection.
   at Starcounter.Core.Db.MetalayerCheck(UInt32 r)
   at StarDump.Core.CrudHelper..ctor(UInt64 dbHandle, ReloadTable table) in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Helpers\CrudHelper.cs:line 47
   at StarDump.Core.Reload.<>c__DisplayClass28_0.<CreateTable>b__0() in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Reload.cs:line 242
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Reload.CreateTables(SqliteConnection cn, List`1 tables) in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Reload.cs:line 209
   at StarDump.Core.Reload.CreateTablesAndInsertData(SqliteConnection cn, Int32& tablesCount, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Reload.cs:line 192
   at StarDump.Core.Reload.Run() in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Reload.cs:line 78
   at StarDump.Core.CommandInterface.Reload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\CommandInterface.cs:line 46
   at StarDump.CommandLineInterface.<>c__DisplayClass10_1.<AddReloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump\CommandLineInterface.cs:line 292
```

Probably this refers to the property [`Something.Deleted`](https://github.com/StarcounterApps/Simplified/blob/master/Ring1/Something.cs#L17) which is in Simplified since August.

@miyconst could you pls help to investigate this? This looks like a bug in StarDump `unload` or `reload`.

![image](https://user-images.githubusercontent.com/566463/32103780-272cb9ae-bb22-11e7-94a7-8ffa8e2cc0b9.png)

**Comment by miyconst** [comment]
This issue happens due to schema mismatch between the dump and the database. Will be fixed after - [Fix partial unload and implement schema less reload](https://github.com/Starcounter/StarDump/issues/71).

Closing.
