### ISSUE TITLE
Fix partial unload and implement schema less reload

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#71]
On today's meeting between me, @warpech and @PatrykSzwer it was decided that StarDump has to be enhanced with the following things:

- When performing partial unload entire database schema has to be unloaded, but actual data is unloaded for specified tables only.
- There should be a schema less reload option. The option should be enabled by a command line parameter like `--schemaless`. In this mode StarDump should not verify the database schema, but reloads the data only. If some tables/columns are missing in the dump or in the database, they should be ignored.

**Comment by PatrykSzwer** [comment]
I just have one question: I'm not sure what will happen when situation like that occur:
I create some schemaless copy of my table data. Then in a meantime, this table will get new, lets say, boolean column. After that I'll reload my copy of table data. Now, what will happen with missing column? It will be just empty, or fulled with default data (e.g. false for boolean)?. I guess it would be empty in this scenario, and question is, if that could cause some troubles later? I think It's worth check scenario.

**Comment by miyconst** [comment]
>I think It's worth check scenario.

Actually, this scenario occurs every time we adjust our database classes with extra column. Existing rows do not have that value, but it's not "empty", it has default value of the specified data type, zero for numbers, false for booleans, null for string.

**Comment by PatrykSzwer** [comment]
O that's great! I wasn't sure if It's done already, not needed or TBD. It's great that It's already handled.

**Comment by miyconst** [comment]
The features has been implemented in the [71-skipschema-reload](https://github.com/Starcounter/StarDump/tree/issues/71-skipschema-reload) branch. Custom build with installer is vailable upon request.

The changes will be merged into master after a couple of days, or when @PatrykSzwer and/or @warpech check that it actually works in their scenario.

The extra parameter available for the `reload` command is: `-noschema` or `--skipschema`.

**Comment by PatrykSzwer** [comment]
I've tested our new awesome `-noschema` function and here are my thoughts:
1. When I tried to use it in a way like this: `stardump.exe reload --database default --file C:\Temp\test.sqlite3 -noschema` I've got ugly, really long exception in the console:
```
System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.))) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.)) ---> System.AggregateException: One or more errors occurred. (ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.) ---> Starcounter.Core.StarcounterException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
   at Starcounter.Core.Database.Transaction.CommitAsync()
   at Starcounter.Core.Database.Transaction.Commit()
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StarDump.Core.Reload.InsertTableData(SqliteConnection cn, ReloadTable table, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 388
   at StarDump.Core.Reload.<>c__DisplayClass28_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 248
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StarDump.Core.Reload.<>c__DisplayClass28_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 259
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StarDump.Core.Reload.CreateTablesAndInsertData(Configuration config, SqliteConnection cn, Int32& tablesCount, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 206
   at StarDump.Core.Reload.Run() in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 78
   at StarDump.Core.CommandInterface.Reload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\CommandInterface.cs:line 46
   at StarDump.CommandLineInterface.<>c__DisplayClass10_1.<AddReloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump\CommandLineInterface.cs:line 298
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (One or more errors occurred. (ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.)) ---> System.AggregateException: One or more errors occurred. (ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.) ---> Starcounter.Core.StarcounterException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
   at Starcounter.Core.Database.Transaction.CommitAsync()
   at Starcounter.Core.Database.Transaction.Commit()
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StarDump.Core.Reload.InsertTableData(SqliteConnection cn, ReloadTable table, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 388
   at StarDump.Core.Reload.<>c__DisplayClass28_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 248
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StarDump.Core.Reload.<>c__DisplayClass28_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 259
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.) ---> Starcounter.Core.StarcounterException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
   at Starcounter.Core.Database.Transaction.CommitAsync()
   at Starcounter.Core.Database.Transaction.Commit()
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StarDump.Core.Reload.InsertTableData(SqliteConnection cn, ReloadTable table, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 388
   at StarDump.Core.Reload.<>c__DisplayClass28_0.<InsertTableData>b__0() in C:\TeamCity\BuildAgent\work\sc-10828\StarDump\src\StarDump.Core\Reload.cs:line 248
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) Starcounter.Core.StarcounterException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
   at Starcounter.Core.Database.Transaction.CommitAsync()
   at Starcounter.Core.Database.Transaction.Commit()
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at System.Threading.Tasks.Task.Execute()<---
<---
<---
```
I think we should show something more readable in situation like that.

2. As @miyconst told me: `--forcereload is automatically set to true if --skipschema is set.` This sentence definitely should be added to readme. 

Except those two looks like our new awesome functionality is working as expected!

**Comment by miyconst** [comment]
1. This exception is coming from Starcounter code, and StarDump can not do much about it. The `A transaction was aborted because a constraint was violated.` exception may occur in many scenarios, and I would not like to load StarDump with different code trying to identify what and why has actually happen.

2. The readme has been updated.

**Comment by warpech** [comment]
> This exception is coming from Starcounter code, and StarDump can not do much about it. The `A transaction was aborted because a constraint was violated.` exception may occur in many scenarios, and I would not like to load StarDump with different code trying to identify what and why has actually happen.

I guess StarDump should wrap this exception to say: "An exception in Starcounter has occured: ...."?

Could this be merged to Starcounter today? Website app needs this badly to be released.

**Comment by miyconst** [comment]
Merged to `master` branch. Closing as done.
