### ISSUE TITLE
Unload exception SDv:0.2.4, SCv2.4.0.4067

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/StarDump#78]
```
System.EntryPointNotFoundException: Unable to find an entry point named 'star_crud_GetPropertyReadHandle' in DLL 'scdbmetalayer'.
   at Starcounter.Core.Interop.sccrud.star_crud_GetPropertyReadHandle(UInt64 context_handle, String class_name, String property_name, UInt64& property_read_handle)
   at Starcounter.Core.Binding.SubClassBuilder.<>c__DisplayClass38_0.<BuildProperty>b__0()
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Binding.SubClassBuilder.BuildProperty(PropertyInfo propInfo)
   at Starcounter.Core.Binding.SubClassBuilder.GenerateImplementation()
   at Starcounter.Core.Binding.ClassBinder.<>c.<BindAllDatabaseClasses>b__0_1(Type t)
   at Starcounter.Core.Database.ProxyMap.RegisterTypesAndLayouts(Dictionary`2 registered, Func`2 factoryMaker)
   at Starcounter.Core.Binding.ClassBinder.BindAllDatabaseClasses()
   at Starcounter.Core.Hosting.Connection.Start()
   at Starcounter.Core.Hosting.DefaultAppHost.Start()
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-11828\StarDump\src\StarDump.Core\Unload.cs:line 50
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-11828\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-11828\StarDump\src\StarDump\CommandLineInterface.cs:line 199

**Comment by miyconst** [comment]
@SenerDemiral thank you for reporting the issue, and sorry that you have to experience it.

Unfortunately StarDump is not yet compatible with Starcounter `2.4`. It will soon.

**Comment by SenerDemiral** [comment]
@miyconst  I have been removed from the Starcounter AB organization.
I think, I was not efficient to contribute enough. 
But I could learn a lot of things from Level 1 issues. 
Is there any way to read level 1 issues?

**Comment by miyconst** [comment]
@SenerDemiral you were removed because some of the Starcounter repositories are now private and are going to contain important private data. We really appreciate your input and the bug reports. Feel free to open issues in the public [Starcounter/Home](https://github.com/Starcounter/Home/issues) repository or ask on StarckOverflow with tag [starcounter](https://stackoverflow.com/questions/tagged/starcounter). Sometimes we are not able to answer and fix the issues immediately, but non of your issues are left unnoticed.

**Comment by SenerDemiral** [comment]
Thank you for your relevance.

**Comment by warpech** [comment]
This blocks https://github.com/Starcounter/Blending/issues/44

**Comment by Mihaiii** [comment]
This blocks https://github.com/Starcounter/level1/issues/2833 .
