### ISSUE TITLE
StarDump is not able to connect to the database in production installation mode

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#79]
When Starcounter is installed in production mode, StarDump is not able to connect and crashes.

**Comment by miyconst** [comment]
When trying to connect with default user:

```
Starcounter.Core.StarcounterException: ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail.
   at Starcounter.Core.Hosting.Connection.ConnectToDataManager(StarcounterOptions options)
   at Starcounter.Core.Hosting.Connection.Start()
   at Starcounter.Core.Hosting.DefaultAppHost.Start()
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump.Core\Unload.cs:line 50
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump\CommandLineInterface.cs:line 199
```

When trying to connect under admin user:

```
Starcounter.Core.StarcounterException: ScErrDataManagerUnavailable (SCERR4293): Failed to connect to data manager is unavailable. Occurs when data manager is not started or not yet properly initialized.
   at Starcounter.Core.Hosting.Connection.ConnectToDataManager(StarcounterOptions options)
   at Starcounter.Core.Hosting.Connection.Start()
   at Starcounter.Core.Hosting.DefaultAppHost.Start()
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump.Core\Unload.cs:line 50
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump\CommandLineInterface.cs:line 199
```

**Comment by miyconst** [comment]
cc @linkdata

**Comment by miyconst** [comment]
```
<PackageReference Include="Starcounter.Core" Version="0.5.0-*" />
```

```
Starcounter-RC-2.3.1.8045 (Dec 10, 2017 1:02:02 AM)
```

**Comment by linkdata** [comment]
> ScErrUnexpPlatformAPIError (SCERR6067): An unexpected error occured calling a platform API function. OS error=5 (CreateFile).
> A fatal error was detected: ScErrTransLogWriterNotAvailable (SCERR4256): Transaction log writer is not available

[scdblog.exe.11156.zip](https://github.com/Starcounter/StarDump/files/1547596/scdblog.exe.11156.zip)

**Comment by miyconst** [comment]
I am getting only the first error reported by @linkdata:

```
ScErrUnexpPlatformAPIError (SCERR6067): An unexpected error occured calling a platform API function. OS error=5 (CreateFile).
```

And crash dump is not generated, although it's [enabled](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx).

**Comment by bigwad** [comment]
I didn't see through the code, but I think there is a bunch of problems:
1. Scdata sets too restrictive access rights on its endpoints (pipes, shared memory, events, etc) or doesn't  put all endpoints into global namespace. As a result stardump running under administrator can't connect to an instance of scdata running under localsystem account.
2. Nova fails to detect existing scdata endpoint and tries to launch another scdata instance. Probably it's a fault of the sccoredb library, so here I don't mean to blame Nova's codebase - just stating it as a fact.
3. When Nova launches scdata - it was meant to detect an instance already running and fail early with some meaningful error.

In the meantime, I can recommend stopping a database before running stardump.

**Comment by miyconst** [comment]
>As a result stardump running under administrator can't connect to an instance of scdata running under localsystem account.

Can we fix it?

>In the meantime, I can recommend stopping a database before running stardump.

Unfortunately this is not possible. One of the main features of StarDump is to be able to unload a live database. When a database startup time takes ~1 hour, it's a very valuable feature.

**Comment by bigwad** [comment]
I'm working on it. "In the meantime" - I mean until it's fixed

**Comment by miyconst** [comment]
Good. Just to note: it has to be fixed in `2.3.1`.

**Comment by bigwad** [comment]
>Good. Just to note: it has to be fixed in 2.3.1.

I understand, although it won't be that easy. We're using IPC in a way that prohibits commination between the database kernel and a client running in different windows sessions (besides restrictive rights). It will take some time to make it work in both development and production scenario.

**Comment by bigwad** [comment]
Fixed. 
If StarCounter is running as a service, one needs to run stardump as an administrator. 
Overwise stardump will fail with 

```
Starcounter.Core.StarcounterException: ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail.
   at Starcounter.Core.Hosting.Connection.ConnectToDataManager(StarcounterOptions options)
   at Starcounter.Core.Hosting.Connection.Start()
   at Starcounter.Core.Hosting.DefaultAppHost.Start()
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump.Core\Unload.cs:line 50
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-11929\StarDump\src\StarDump\CommandLineInterface.cs:line 199
```

Additional notes:
1. With this error message, a user has no idea on the reason of the error. This is because kernel connection API error reporting is insufficient. It writes native error code (5 in this case, which is `access denied`) to the database log instead of returning it to a client. Should be fixed separately. 
2. Until item#1 is done, stardump may give user a suggestion on possible reason and point to database log for details
3. We should consider automated testing of production scenarios. cc @ubbeK 
4. Kernel tries to restrict an access to a database, but it makes no sense until scservice provides some authentication.

**Comment by bigwad** [comment]
Doesn't work if starcounter service is running under a non-administrative account. Working on it.

**Comment by bigwad** [comment]
Fixed for non-administrative server account also.

**Comment by miyconst** [comment]
Tested. Thank you @bigwad.
