### ISSUE TITLE
Typo in an exception message: a missing space

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#83]
```
Starcounter.Core.StarcounterException
  HResult=0x80131500
  Message=ScErrSchemasDoNotMatch (SCERR15009): Schema of given type does not match with schema of the existing type. Schema of the input type does not match schema of existing type: StarDump.Core.DbProxyItemmore input columns than existing.

  Source=Starcounter.Core.Database
  StackTrace:
   at Starcounter.Core.Database.DbImpl.MetalayerCheck(UInt32 r)
   at Starcounter.Core.Binding.ClassBinder.<>c__DisplayClass10_0.<BindToDatabase>b__0()
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Database.TransactImpl.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Binding.ClassBinder.BindToDatabase(Type type, Dictionary`2 registered)
   at Starcounter.Core.Binding.ClassFinder.ForEachReferencingAssemblyClassWithAttribute(String assemblyName, String attributeName, Action`1 action)
   at Starcounter.Core.Binding.ClassBinder.BindAllDatabaseClasses()
   at Starcounter.Core.Hosting.Connection.Start()
   at Starcounter.Core.Hosting.DefaultAppHost.Start()
   at StarDump.Core.AppHostHelper.BuildAndStartAppHost(String[] args, Configuration config) in C:\Users\Const\Documents\GitHub\StarDump\src\StarDump.Core\Helpers\AppHostHelper.cs:line 25
   at StarDump.Core.AppHostHelper.BuildAndStartAppHost(Configuration config) in C:\Users\Const\Documents\GitHub\StarDump\src\StarDump.Core\Helpers\AppHostHelper.cs:line 17
   at StarDump.Core.Unload.Run() in C:\Users\Const\Documents\GitHub\StarDump\src\StarDump.Core\Unload.cs:line 46
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\Users\Const\Documents\GitHub\StarDump\src\StarDump.Core\CommandInterface.cs:line 74
   at StarDump.Core.Program.Main(String[] args) in C:\Users\Const\Documents\GitHub\StarDump\src\StarDump.Core\Program.cs:line 29
```

The typo is here: 

>StarDump.Core.DbProxyItemmore input columns than existing.

Should be:

>StarDump.Core.DbProxyItem more input columns than existing.

**Comment by miyconst** [comment]
Wrong repository - [Typo in an exception message: a missing space](https://github.com/Starcounter/Starcounter.Core/issues/237).
